#!/usr/bin/env python3
"""Generate a deployable agent directory for each role in roles.py.

    python3 agents/build.py              # generate all five
    python3 agents/build.py discovery    # just one

Output lands in agents/build/<role>/, which is git-ignored — it is derived,
not source. Edit roles.py or _template/, never agents/build/.

Each generated directory is a complete Nasiko agent: Dockerfile, AgentCard.json
and src/. The only file that differs between them is src/role.py, which carries
the role's title, prompt and tool list.
"""

import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(HERE, "_template")
OUT = os.path.join(HERE, "build")

sys.path.insert(0, HERE)
from roles import COMMON, ROLES  # noqa: E402

ROLE_PY = '''\
"""Generated by agents/build.py from agents/roles.py. Do not edit."""

TITLE = {title!r}
DESCRIPTION = {description!r}
SKILL_ID = {skill_id!r}
SKILL_NAME = {skill_name!r}
TAGS = {tags!r}
EXAMPLES = {examples!r}

# The authority boundary: only these tools are bound to the agent.
TOOL_NAMES = {tools!r}
WRITES_SOURCE = {writes_source!r}

INSTRUCTIONS = """{instructions}"""
'''


def agent_card(key, role, url_port):
    return {
        "protocolVersion": "0.2.9",
        "name": "stackshift-%s" % key,
        "description": role["description"],
        "url": "http://localhost:%d/" % url_port,
        "agentFramework": "openai-agents",
        "preferredTransport": "JSONRPC",
        "provider": {"organization": "StackShift", "url": "https://github.com/arnavgupta28/StackShift"},
        "version": "1.0.0",
        "capabilities": {
            "streaming": True,
            "pushNotifications": False,
            "stateTransitionHistory": False,
        },
        "securitySchemes": {},
        "security": [],
        "defaultInputModes": ["text/plain"],
        "defaultOutputModes": ["text/plain"],
        "skills": [{
            "id": role["skill_id"],
            "name": role["skill_name"],
            "description": role["description"],
            "tags": role["tags"],
            "examples": role["examples"],
            "inputModes": ["text/plain"],
            "outputModes": ["text/plain"],
        }],
        # Not read by Nasiko — recorded so the deployed fleet's permissions are
        # auditable from the artifact itself.
        "x-stackshift": {
            "role": key,
            "tools": role["tools"],
            "writes_source": role["writes_source"],
        },
    }


def build(key, role, port):
    dest = os.path.join(OUT, key)
    if os.path.isdir(dest):
        shutil.rmtree(dest)
    shutil.copytree(TEMPLATE, dest)

    instructions = COMMON + "\n" + role["instructions"]
    if '"""' in instructions:
        raise ValueError("role %s: instructions contain a triple quote" % key)

    with open(os.path.join(dest, "src", "role.py"), "w") as fh:
        fh.write(ROLE_PY.format(
            title=role["title"],
            description=role["description"],
            skill_id=role["skill_id"],
            skill_name=role["skill_name"],
            tags=role["tags"],
            examples=role["examples"],
            tools=role["tools"],
            writes_source=role["writes_source"],
            instructions=instructions,
        ))

    with open(os.path.join(dest, "AgentCard.json"), "w") as fh:
        json.dump(agent_card(key, role, port), fh, indent=2)
        fh.write("\n")

    return dest, len(role["tools"])


def main():
    wanted = sys.argv[1:] or list(ROLES)
    unknown = [w for w in wanted if w not in ROLES]
    if unknown:
        print("unknown role(s): %s" % ", ".join(unknown))
        print("available: %s" % ", ".join(ROLES))
        return 1

    os.makedirs(OUT, exist_ok=True)
    print()
    for i, key in enumerate(wanted):
        dest, ntools = build(key, ROLES[key], 10010 + list(ROLES).index(key))
        flag = "WRITES SOURCE" if ROLES[key]["writes_source"] else "read-only"
        print("  built %-12s %d tools  %-13s -> %s"
              % (key, ntools, flag, os.path.relpath(dest)))
    print()
    print("  %d agent(s) generated in agents/build/" % len(wanted))
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
